services:
  quarkus_db:
    image: postgres
    container_name: postgres-db-inventory-quarkus
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: quarkus_app_inventory
    volumes:
      - postgres:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
  quarkus-inventory-app:
    container_name: quarkus-inventory-app
    build:
      context: .
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - quarkus_db
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: jdbc:postgresql://quarkus_db:5432/quarkus_app_inventory
      QUARKUS_DATASOURCE_USERNAME: username
      QUARKUS_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8081"
volumes:
  postgres:
    driver: local